# Generated by Django 4.2 on 2023-04-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('Last_name', models.CharField(max_length=255, verbose_name='Second name')),
                ('Email_address', models.EmailField(max_length=254)),
                ('Confirm_email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.event', verbose_name='Event')),
            ],
        ),
    ]
