# Generated by Django 4.2 on 2023-04-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_makereservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makereservation',
            old_name='First_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='makereservation',
            name='Last_name',
        ),
    ]
