# Generated by Django 4.2 on 2023-04-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_first_name_makereservation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makereservation',
            name='Confirm_email',
        ),
    ]
