# Generated by Django 4.2 on 2023-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_makereservation_confirm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='makereservation',
            name='Number_of_guest',
            field=models.IntegerField(null=True),
        ),
    ]
