# Generated by Django 4.2 on 2023-04-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_makereservation_number_of_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='private_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
